story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.index, name='index'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.index, name='index'),
    path('livre/', views.livre, name='livre')
]

story9/urls.py
from django.urls import path

from . import views

app_name = 'story9'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.logging_in, name='logging_in'),
    path('logout/', views.logging_out, name='logging_out')
]

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class RegistrationForm(UserCreationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Nom d'Utilisateur"
    }))

    password1 = forms.CharField(label="Password", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Mot de Passe",
        "type" : "password"
    }))

    password2 = forms.CharField(label="Confirm Password*", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Confirmez Le Mot de Passe",
        "type" : "password"
    }))

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Nom d'Utilisateur"
    }))

    password = forms.CharField(label="Password", widget=forms.TextInput(attrs={
        "class" : "form-control mb-3",
        "placeholder" : "Mot de Passe",
        "type" : "password"
    }))

    class Meta:
        fields = "__all__"

story7/views.py
from django.shortcuts import render
from django.contrib.auth.models import User

#this is the views
def index(request):
    context = {
        "page" : "storys7",
        "namanya" : request.user.username
    }
    return render(request, "story7/index.html", context)

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
import urllib3
import json

#Story 8
@login_required(login_url="/story9/login")
def index(request):
    context = {
        "page" : "storys8",
        "namanya" : request.user.username
    }
    return render(request, "story8/index.html", context)

def livre(request):
    http = urllib3.PoolManager()
    response = http.request(
        "GET", "https://www.googleapis.com/books/v1/volumes?q=" + request.GET.get('q', ''))
    return JsonResponse(json.loads(response.data.decode('utf8')))

story9/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login , logout, authenticate
from django.contrib.auth.models import User
from .forms import RegistrationForm, LoginForm, AuthenticationForm

# Login System
def register(request):
    if request.user.is_authenticated:
        return redirect("story7:index")
    context = {
        "registering":RegistrationForm,
        "page":"storys9",
        "type":"registre"
    }

    if request.method == "POST":
        registering = RegistrationForm(request.POST)
        if registering.is_valid():
            registering.save()
            new_user_account = authenticate(
                username = registering.cleaned_data['username'],
                password = registering.cleaned_data['password1']
            )
            login(request, new_user_account)

            return redirect("story7:index")
        elif registering.errors:
            context["error"] = "There is something wrong with your inputs!"
    return render(request, 'story9/register.html', context)

def logging_in(request):
    context = {"logging_in": LoginForm, "page":"storys9","type":"login"}
    if request.user.is_authenticated:
        return redirect("story7:index")

    if request.method == "POST":
        logging_in = LoginForm(data = request.POST)
        if logging_in.is_valid():
            user_account = logging_in.get_user()
            login(request, user_account)
            return redirect("story7:index")
        elif logging_in.errors:
            context["error"] = "Wrong Username or Password"
    return render(request, 'story9/login.html', context)

def logging_out(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("story7:index")

story7/templates/story7/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block meta %}
    {% endblock meta %}
    <link href="https://fonts.googleapis.com/css2?family=Comic+Neue&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'story7/css/styles.css' %}">
    <link rel="shortcut icon" type="image/JPG" href="{% static 'story7/pic/logo.JPG' %}">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </head>
  <body style="background-image: url(https://secretcompass.com/wp-content/uploads/2019/04/a-walk-on-lebanon-cover.jpg);" style="background-attachment: fixed;"> <!-- Background taken from secretcompass.com-->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-footer-bg shadow-lg">
        {% if page == "storys7" and request.user.is_authenticated %}
          <div class="container">
              <a class="navbar-brand bg-dark" id="webappname" href="{% url 'story7:index' %}">Le profile de {{ namanya }}</a>
          </div>
        {% elif page == "storys7" and not request.user.is_authenticated %}
        <div class="container">
          <a class="navbar-brand bg-dark" id="webappname" href="{% url 'story9:register' %}">Faire un compte</a>
        </div>
        {% elif page == "storys8" and request.user.is_authenticated %}
          <div class="container">
              <a class="navbar-brand bg-dark" id="webappname" href="{% url 'story8:index' %}">La Bibliothèque de {{ namanya }}</a>
          </div>
        {% elif page == "storys8" and not request.user.is_authenticated %}
        <div class="container">
          <a class="navbar-brand bg-dark" id="webappname" href="{% url 'story9:register' %}">Faire un compte</a>
        </div>
        {% elif page == "storys9" and type == "login" %}
        <div class="container">
          <a class="navbar-brand bg-dark" id="webappname" href="#">Login</a>
        </div>
        {% elif page == "storys9" and type == "registre" %}
        <div class="container">
          <a class="navbar-brand bg-dark" id="webappname" href="#">Registre</a>
        </div>
        {% else %}
          <div class="container">
              <a class="navbar-brand bg-dark" id="webappname" href="#">N'est pas Disponible</a>
          </div>
        {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" style="justify-content: center;" id="navbarNavDropdown">
          <ul class="navbar-nav" style="margin: auto;">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'story7:index' %}">Story 7</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'story8:index' %}">Story 8</a>
          </li>
        </ul>
            <div class="navbar-nav">
              {% if not request.user.is_authenticated %}
              <a href="{% url 'story9:logging_in' %}" class="nav-item nav-link button-login">LOGIN</a>
              <a href="{% url 'story9:register' %}" class="nav-item nav-link button-signup">REGISTRE</a> 
              {% else %}
              <a href="{% url 'story9:logging_out' %}" class="nav-item nav-link button-signup">SE DÉCONNECTER</a>

              {% endif %}
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <footer class="footer navbar-footer-bg align-items-center text-light justify-content-center shadow-lg d-flex">
        <p> Droits d'auteur : Matthew T.P. Solomon </p>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'story7/js/script.js' %}"></script>
</body>
</html>

story7/templates/story7/index.html
{% extends "story7/base.html" %}
{% load static %}
{% block meta %}
<title>Le Profile de Monsieur Matthew</title>
{% endblock meta %}
{% block content %}
<div class="d-flex flex-column justify-content-start align-items-center py-5 col-lg-8 mx-auto">
    {% if request.user.is_authenticated %}
    <div>
        <h1 class="p-2 m-0 accordion-tab text-light bg-dark" style="font-family: Brush Script MT;">
            Bienvenue ici {{ namanya }}
        </h1>
    </div>
    <div>
        <p><br> <br> <br> </p>
    </div>
    {% endif %}

    <div class="col-lg-6 col-sm-12 h-main d-flex justify-content-center align-items-center flex-column">
        <img class="w-50 bg-dark p-2 rounded-lg" src="{% static 'story7/pic/profpic.jpg' %}">
        <div class="mt-2 bg-dark text-light p-1 rounded-lg">
            <p>Matthew T.P. Solomon</p>
        </div>
    </div>
    <section class="h-main container-fluid" id="main-bg">
        <div class="col-lg-6 col-sm-12 h-main p-2">
            <div id="accordion">
                <h3 position="0" class="p-2 m-0 accordion-tab text-light bg-dark">
                    Je Suis Qui
                    <span class="mx-1 float-right down" id="down">
                        ↓
                    </span>
                    <span class="mx-1 float-right up" id="up">
                        ↑
                    </span>
                </h3>
                <p position="0" class="p-1 m-0 bg-success text-light bg-info">
                    Salut, je suis un Indonésien qu'est content d'apprendre des langues
                </p>
                <h3 position="1" class="p-2 m-0 accordion-tab text-light bg-dark">
                    Mes Loisirs
                    <span class="mx-1 float-right down" id="down">
                        ↓
                    </span>
                    <span class="mx-1 float-right up" id="up">
                        ↑
                    </span>
                </h3>
                <p position="1" class="p-1 m-0 bg-success text-light bg-info">
                    Je suis content d'apprendre des langues, ces sont elles<br>    * Allemand<br>    * Français<br>    * Roumain<br><br>
                    J'adore de faire ces activités<br>    * Cuisiner<br>    * Dormir<br>    * Regarder des Animes<br>
                </p>
                <h3 position="2" class="p-2 m-0 accordion-tab text-light bg-dark">
                    Veux etre quoi?
                    <span class="mx-1 float-right down" id="down">
                        ↓
                    </span>
                    <span class="mx-1 float-right up" id="up">
                        ↑
                    </span>
                </h3>
                <p position="2" class="p-1 m-0 bg-success text-light bg-info">
                    * Ingénieur sur l'informatique <br> * Scientifique des Données <br> * Un Père <br> * Un Mari
                </p>
                <h3 position="3" class="p-2 m-0 accordion-tab text-light bg-dark">
                    Contactez-Moi
                    <span class="mx-1 float-right down" id="down">
                        ↓
                    </span>
                    <span class="mx-1 float-right up" id="up">
                        ↑
                    </span>
                </h3>
                <p position="3" class="p-1 m-0 bg-success text-light bg-info">
                    Je Suis Disponible sur Instagram : <a href="https://www.instagram.com/matthewsolomon_/?hl=en" class="text-light">
                        @matthewsolomon_
                    </a>
                </p>
                <h3 position="4" class="p-2 m-0 accordion-tab text-light bg-dark">
                    Votre occupation?
                    <span class="mx-1 float-right down" id="down">
                        ↓
                    </span>
                    <span class="mx-1 float-right up" id="up">
                        ↑
                    </span>
                </h3>
                <p position="4" class="p-1 m-0 bg-success text-light bg-info">
                    Je suis étudiant à UI
                </p>
                <h3 position="5" class="p-2 m-0 accordion-tab text-light bg-dark">
                    Mes Animations
                    <span class="mx-1 float-right down" id="down">
                        ↓
                    </span>
                    <span class="mx-1 float-right up" id="up">
                        ↑
                    </span>
                </h3>
                <video position="5" controls class="p-1 m-0 rounded shadow-lg bg-info">
                    <source src="{% static 'story7/video/baka-mitai.mp4' %}" type="video/mp4">
                </video>
            </div>
        </div>

    </section>
</div>
{% endblock %}

story8/templates/story8/index.html
{% extends "story7/base.html" %}
{% load static %}
{% block meta %}
<title>La bibliothèque de Monsieur Matthew</title>
{% endblock meta %}
{% block content %}
<div class="jumbotron bg-main3 text-light rounded-0 m-0" style="background-color: rgba(2, 18, 32, 0.503);">
    <div class="container">
        <h1 class="display-4" style="font-family: Brush Script MT;">Bonjour à Vous {{ namanya }} <br> à La bibliothèque de Monsieur Matthew</h1>
        <p class="lead" style="font-family: Brush Script MT;">Ici, Vous pouvez rechercher vos livres préférés</p>
        <hr class="my-4">
        <p style="font-family: Brush Script MT;">Ceci est créé par Monsieur Matthew</p>
        <p class="lead">
        <div class="d-flex">
            <input type="text" id="keyword" class="form-control w-25 mr-1" placeholder="Le Livre">
            <button class="btn btn-main1 bg-dark text-light" id="searchword" role="button" style="font-family: Brush Script MT;">Rechercher</button>
        </div>
        </p>
    </div>
</div>
<section class="bg-main3 text-light p-3 result-section">
    <h1 class="text-center p-0 m-0" id="otoko">Voici les résultats : </h1>
    <ul id="resultat" class="d-flex flex-column align-items-center">
        <h1 class="m-5">{{ namanya }}, Vous n'avez pas cherché pour un livre</h1>
        <div class="col-lg-6 col-sm-12 h-main d-flex justify-content-center align-items-center flex-column">
            <img class="w-50 bg-dark p-2" style="border-radius: 50%;" src="{% static 'story8/pic/gomenasai.gif' %}">
        </div>
    </ul>
</section>
<script type="text/javascript">
    $(document).ready(function(){
        $("#searchword").click(() => {
            var otokocolour = "#041e21";
            var otokocurves = "Brush Script MT";
            var titles = $("#keyword").val();
            var called = 'https://www.googleapis.com/books/v1/volumes?q=' + titles;
            $("#otoko").css("font-family", otokocurves)
            $("#otoko").css("color", otokocolour)
            getResultat();
        })
    });
    
    function getResultat() {
        $.ajax({
            url: window.location.origin + "/story8/livre/?q=" + $( '#keyword' ).val(),
            success : function(resultat){
                var obj_resultat = $("#resultat");
                obj_resultat.empty();

                if (resultat.items.length != 0){
                    for (x = 0 ; x < resultat.items.length ; x++){
                        var generalement = resultat.items[x];
                        var temp_titre = generalement.volumeInfo.title;
                        var infos = generalement.volumeInfo.infoLink;
                        try {
                            var imge = generalement.volumeInfo.imageLinks.thumbnail;
                        } catch {
                            var imge = "https://hg1.funnyjunk.com/thumbnails/comments/Anybody+can+be+sick+of+any+job+on+some+days+_92b8ed051ccb2daa44c0fcbcef26e6f0.jpg";
                        }
                        var datespublicite = generalement.volumeInfo.publishedDate;
                        var descriptions = generalement.volumeInfo.description ? generalement.volumeInfo.description : "Il n y a pas de description"
                        obj_resultat.append(
                            `<div class="card w-75 border-dark m-3">
                                <h3 class="card-header bg-main1 text-center text-left-lg bg-dark">
                                    <a target="_blank" class="book-link text-light" href="${infos}">
                                        ${temp_titre}
                                    </a>
                                </h3>
                                <div class="card-body bg-main2" style="background-color: rgba(2, 18, 32, 0.503);">
                                    <div class="row">
                                        <div class="col-lg-9 col-12 book-info">
                                            <h5 class="card-title">Published on ${datespublicite}</h5>
                                            <p class="card-text text-justify">${descriptions}</p>
                                        </div>
                                        <div class="col-lg-3 col-12 d-flex align-items-center justify-content-center">
                                            <img class="mr-3 book-cover" src="${imge}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            `
                        )
                    }
                }
            }
        });
    }

</script>
{% endblock %}

story9/templates/story9/login.html
{% extends 'story7/base.html' %}
{% load static %}

{% block meta %}
<title>login</title>
{% endblock meta %}

{% block content %}
<section class="main-section d-flex justify-content-center align-items-center text-dark" style="height: 100vh;">
    <form method="POST" action="{% url 'story9:logging_in' %}" class="login-form bg-light rounded-lg d-flex flex-column justify-content-center p-4">
        {% if error %}
            <p class="text-center p-2 bg-danger rounded-lg">{{error}}</p>
        {% endif %}
        <h3 class="mb-3 text-center">INSÉRER UN COMPTE</h3>
        {% csrf_token %}
        {{logging_in}}
        <button id="btn_login" type="submit" class="btn btn-dark" style="padding: 10px 30px; border:none; border-radius:100px 100px 100px 100px">Login</button>
        <div class="card-footer">
            <div class="d-flex justify-content-center links">
                Vous n'avez pas du compte?<a href="{% url 'story9:register' %}">Créez-en Un</a>
            </div>
        </div>
    </form>
</section>
{% endblock %}

story9/templates/story9/register.html
{% extends 'story7/base.html' %}
{% load static %}

{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}
<section class="registration-section d-flex justify-content-center align-items-center text-dark flex-column" style="height: 100vh;">
    {% if error %}
            <p class="text-center p-2 bg-danger rounded-lg">
                {{error}}
            </p>
            <p class="text-center p-2 bg-danger rounded-lg">
                * Il doit y avoir au moins 9 caractères<br>
                * Assurez-vous qu'il y a au moins 5 lettres
            </p>
    {% endif %}
    <form method="POST" action="{% url 'story9:register' %}" class="login-form bg-light rounded-lg d-flex flex-column justify-content-center p-4">
        <h3 class="text-center mb-3">CRÉER UN COMPTE</h3>
        {% csrf_token %}
        {{registering}}
        <button type="submit" id="btn_register" class="btn btn-dark" style="padding: 10px 30px; border:none; border-radius:100px 100px 100px 100px">Registre</button>
    </form>

</section>
{% endblock %}